docs_dir: docs/
site_name: Cubed Documentation
site_url: 'https://wiki.cubed-mc.com'
repo_url: 'https://github.com/cubed-mc/cubed-wiki'
repo_name: 'cubed-mc/cubed-wiki'
site_description: 'Cubed is a private Minecraft SMP server with an invite-only community. Show good interest and you might just receive an invite.'
site_author: 'Cubed'
copyright: '© 2021 Cubed. All rights reserved.'
nav:
    - 'Home': 'index.md'
    - 'About':
        - 'Overview': 'about/overview.md'
        - 'What is: Cubed Minecraft': 'cubedsmp/minecraft-about.md'
        - 'What is: Cubed Discord': 'about/discord-about.md'
        - 'What is: Cubed Mumble': 'about/mumble-about.md'
    - 'Servers':
        - 'Overview': 'servers/overview.md'
        - 'Cubed Minecraft':
          - 'Apply for whitelist': 'resources/whitelist-request.md'
          - 'Commands': 'cubedsmp/commands.md'
          - 'Features': 'servers/minecraft/features.md'
          - 'Frequently Asked Questions': 'cubedsmp/aq.md'
        - 'Cubed Discord':
          - 'Apply for whitelist': 'resources/whitelist-request.md'
          - 'Commands': 'servers/discord/commands.md'
          - 'Ticket Categories': 'servers/discord/ticket-categories.md'
          - 'Frequently Asked Questions': 'servers/discord/faq.md'
        - 'Cubed Mumble':
          - 'Enable Proximity Chat': 'servers/mumble/proximity-chat.md'
          - 'Frequently Asked Questions': 'servers/mumble/faq.md'
    - 'CubedSMP':
        - 'What is: Cubed Minecraft': 'cubedsmp/minecraft-about.md'
        - 'Apply for whitelist': 'resources/whitelist-request.md'
        - 'Commands': 'cubedsmp/commands.md'
        - 'Gameplay':
          - 'Drugs': 'cubedsmp/gameplay/drugs.md'
          - 'Weapons': 'cubedsmp/gameplay/weapons.md'
        - 'Frequently Asked Questions': 'cubedsmp/faq.md'
    - 'Resources':
        - 'Whitelist Request': 'resources/whitelist-request.md'
        - 'Staff Applications': 'resources/apply-staff.md'
        - 'Appeal a Punishment': 'resources/appeal-punishment.md'
    - 'Credits': 'credits.md'
    - 'Support': 'support.md'
theme:
  name: 'material'
  palette:
      scheme: slate
      primary: black
      accent: orange
  font:
      text: Inter
      code: Source Code Pro
  language: en
  direction: ltr
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
  markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
extra:
  homepage: https://wiki.cubed-mc.com
  social:
    - icon: fontawesome/solid/globe
      link: https://cubed-mc.com/
    - icon: fontawesome/brands/discord
      link: https://discord.cubed-mc.com/
    - icon: fontawesome/brands/github
      link: https://github.com/cubed-mc/
plugins:
  - search:
      lang: en
      prebuild_index: true
markdown_extensions:
  - admonition
