docs_dir: docs/
site_name: Cubed Documentation
site_url: 'https://wiki.cubed-mc.com'
repo_url: 'https://github.com/cubed-mc/cubed-wiki'
repo_name: 'cubed-mc/cubed-wiki'
site_description: 'Cubed is a private Minecraft SMP server with an invite-only community. Show good interest and you might just receive an invite.'
site_author: 'Cubed'
copyright: '© 2021 Cubed. All rights reserved.'
nav:
    - 'Home': 'index.md'
    - 'Servers':
        - 'Overview': 'servers/overview.md'
        - 'Cubed Minecraft':
          - 'What is Cubed Minecraft?': 'servers/minecraft/about.md'
        - 'Cubed Discord':
          - 'What is Cubed Discord?': 'servers/discord/about.md'
    - 'Cubed':
        - 'Get Invited': 'cubed/get-invite.md'
        - 'Connect to Cubed': 'cubed/connect-cubed.md'
        - 'Setup Proximity Chat': 'cubed/proximity-chat.md'
    - 'Gameplay':
        - 'Drugs': 'gameplay/drugs.md'
        - 'Weapons': 'gameplay/weapons.md'
    - 'Resources':
        - 'In-game Commands': 'resources/ingame-commands.md'
        - 'Discord Ticket System': 'resources/discord-tickets.md'
theme:
  name: 'material'
  palette:
      primary: black
      accent: amber
  font:
      text: Roboto
      code: JetBrains Mono
  language: en
  direction: ltr
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
  markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
extra:
  homepage: https://wiki.cubed-mc.com
  social:
    - icon: fontawesome/solid/globe
      link: https://cubed-mc.com/
    - icon: fontawesome/brands/discord
      link: https://discord.cubed-mc.com/
    - icon: fontawesome/brands/github
      link: https://github.com/cubed-mc
plugins:
  - search:
      lang: en
      prebuild_index: true
markdown_extensions:
  - admonition
