docs_dir: docs/
site_name: Cubed Wiki
site_url: 'https://cubed-wiki.williamhallin.com'
repo_url: 'https://github.com/whallin/cubed-wiki'
repo_name: 'whallin/cubed-wiki'
site_description: 'Cubed is a private Swedish Minecraft SMP server with an invite-only community. Show good interest and you might just receive an invite.'
site_author: 'William Hallin'
copyright: '© 2021 Cubed, trademark of Newgent Digital. All rights reserved.'
nav:
    - Hem: 'index.md'
theme:
  name: 'material'
  palette:
      primary: black
      accent: amber
  font:
      text: Roboto
      code: JetBrains Mono
  language: en
  direction: ltr
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
  markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
docs_dir: docs/
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Svenska
      link: sv/
      lang: sv
  homepage: https://cubed-wiki.williamhallin.com
plugins:
  - search:
      lang:
        - en
        - sv
      prebuild_index: true
