docs_dir: docs/
site_name: Cubed Wiki
site_url: 'https://wiki.cubed-mc.com'
repo_url: 'https://github.com/cubed-mc/cubed-wiki'
repo_name: 'cubed-mc/cubed-wiki'
site_description: 'Cubed is a private Minecraft SMP server with an invite-only community. Show good interest and you might just receive an invite.'
site_author: 'Cubed'
copyright: '© 2021 Cubed. All rights reserved.'
nav:
    - 'Home': 'index.md'
    - 'Getting started':
        - 'Get Invited': 'start/get-invite.md'
        - 'Connect to Cubed': 'start/connect-cubed.md'
        - 'Setup Proximity Chat': 'start/proximity-chat.md'
    - 'Gameplay':
        - 'Drugs': 'gameplay/drugs.md'
        - 'Weapons': 'gameplay/weapons.md'
        - 'Gangs': 'gameplay/gangs.md'
    - 'Reference':
        - 'In-game Commands': 'reference/ingame-commands.md'
        - 'Discord Ticket System': 'reference/discord-tickets.md'
theme:
  name: 'material'
  palette:
      primary: black
      accent: amber
  font:
      text: Roboto
      code: JetBrains Mono
  language: en
  direction: ltr
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
  markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
extra:
  homepage: https://wiki.cubed-mc.com
plugins:
  - search:
      lang: en
      prebuild_index: true
markdown_extensions:
  - admonition
