docs_dir: sv/docs/
site_name: Cubed Wiki
site_url: 'https://cubed-wiki.williamhallin.com/sv/'
repo_url: 'https://github.com/whallin/cubed-wiki'
repo_name: 'whallin/cubed-wiki'
site_description: 'Cubed is a private Minecraft SMP server with an invite-only community. Show good interest and you might just receive an invite.'
site_author: 'William Hallin'
copyright: '© 2021 Cubed, trading as Newgent Digital. All rights reserved.'
nav:
    - 'Home': 'index.md'
    - 'User Guide':
        - 'Join Cubed': 'user-guide/join-cubed.md'
        - 'Setup Proximity Chat': 'user-guide/proximity-chat.md'
        - 'In-game Commands': 'user-guide/ingame-commands.md'
    - 'Gameplay Guide':
        - 'Economy': 'gameplay-guide/economy.md'
        - 'Drugs': 'gameplay-guide/drugs.md'
        - 'Weapons': 'gameplay-guide/weapons.md'
        - 'Gangs': 'gameplay-guide/gangs.md'
theme:
  name: 'material'
  palette:
      primary: black
      accent: amber
  font:
      text: Roboto
      code: JetBrains Mono
  language: sv
  direction: ltr
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
  markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
extra:
  homepage: https://cubed-wiki.williamhallin.com/sv/
  alternate:
    - name: English
      link: https://cubed-wiki.williamhallin.com/en
      lang: en
    - name: Svenska
      link: https://cubed-wiki.williamhallin.com/sv/
      lang: sv
plugins:
  - search:
      lang:
        - en
        - sv
      prebuild_index: true
